#!/usr/bin/env python3
"""Collect installed production dependency notices without network access.

Run after `npm ci` and before the frontend build. `--check` verifies that the
committed notice matches the lockfile and installed package license files.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
OUTPUT = FRONTEND / "public" / "THIRD_PARTY_NOTICES.txt"
NOTICE_NAME = re.compile(r"^(?:licen[sc]e|copying|notice)(?:[._-].*)?$", re.IGNORECASE)
LICENSE_SECTION = re.compile(r"^(#{1,6})\s+licen[sc]e\b[^\n]*\n", re.IGNORECASE | re.MULTILINE)


def license_sources(directory):
    """Preserve complete distributed notices, or a README's license section."""
    sources = []
    for path in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if path.is_file() and NOTICE_NAME.fullmatch(path.name):
            content = path.read_text(encoding="utf-8-sig").strip()
            if content:
                sources.append((path.name, content))
    if sources:
        return sources
    # murmurhash-js 1.0.0 distributes its full MIT grant in README.md.
    for path in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if not path.is_file() or not path.name.casefold().startswith("readme"):
            continue
        content = path.read_text(encoding="utf-8-sig")
        match = LICENSE_SECTION.search(content)
        if match:
            tail = content[match.end():]
            next_section = re.search(r"^#{1,%s}\s" % len(match.group(1)), tail, re.MULTILINE)
            text = tail[:next_section.start()] if next_section else tail
            if text.strip():
                return [(path.name + " (License section)", text.strip())]
    raise ValueError("No distributed license text found for %s" % directory.relative_to(FRONTEND))


def collect():
    lock_bytes = (FRONTEND / "package-lock.json").read_bytes()
    lock = json.loads(lock_bytes)
    if lock.get("lockfileVersion") not in (2, 3) or not isinstance(lock.get("packages"), dict):
        raise ValueError("An npm lockfile with a packages inventory is required.")
    entries = []
    for location, metadata in sorted(lock["packages"].items()):
        if not location or metadata.get("dev"):
            continue
        directory = FRONTEND / location
        if not location.startswith("node_modules/") or not directory.resolve().is_relative_to((FRONTEND / "node_modules").resolve()):
            raise ValueError("Unexpected package location: %s" % location)
        manifest = directory / "package.json"
        if not manifest.is_file():
            raise ValueError("%s is not installed; run npm ci in frontend first." % location)
        package = json.loads(manifest.read_text(encoding="utf-8"))
        name, version = package["name"], package["version"]
        if version != metadata.get("version"):
            raise ValueError("Installed %s version differs from package-lock.json; run npm ci." % name)
        license_id = metadata.get("license") or package.get("license") or "See distributed text below"
        if not isinstance(license_id, str):
            license_id = json.dumps(license_id, sort_keys=True)
        sources = license_sources(directory)
        section = ["=" * 78, "%s @ %s" % (name, version), "Declared license: %s" % license_id,
                   "Package location: %s" % location, "=" * 78]
        for filename, text in sources:
            section.extend(["", "Source: %s" % filename, "", text])
        entries.append("\n".join(section))
    if not entries:
        raise ValueError("No production dependencies were found.")
    header = ["THIRD-PARTY FRONTEND NOTICES", "",
              "Generated by scripts/collect-frontend-licenses.py from installed package files.",
              "Inventory: all non-development packages in frontend/package-lock.json.",
              "This includes transitive declarations and type packages declared as runtime",
              "dependencies; the bundler may omit unused portions. Original copyright and",
              "license notices are reproduced below without replacing their terms.", "",
              "Package count: %s" % len(entries),
              "Lockfile SHA-256: %s" % hashlib.sha256(lock_bytes).hexdigest()]
    return "\n".join(header) + "\n\n" + "\n\n".join(entries) + "\n", len(entries)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the existing notices without writing")
    args = parser.parse_args()
    try:
        content, count = collect()
        if args.check:
            if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
                parser.exit(1, "Frontend notices are missing or stale. Run this script without --check.\n")
            print("Verified notices for %s production packages." % count)
        else:
            OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT.write_text(content, encoding="utf-8")
            print("Collected notices for %s production packages: %s" % (count, OUTPUT.relative_to(ROOT)))
    except (OSError, ValueError, KeyError) as exc:
        parser.exit(1, str(exc) + "\n")


if __name__ == "__main__":
    main()
